name: deploy springboot demos
on:
  push:
#    tags:
#      - v*
  workflow_dispatch: {}

jobs:
  build-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package -DskipTests
      - uses: actions/upload-artifact@v2
        with:
          name: demos.jar
          path: target/*.jar

  build-image:
    runs-on: ubuntu-latest
    needs:
      - build-springboot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: demos.jar
          path: target/
      - id: publish-docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: bcblr/demos
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
    outputs:
      tag: ${{ steps.publish-docker.outputs.tag }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-image
    steps:
      - uses: actions/checkout@v2
      - name: copy docker-compose.yml file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "docker-compose.yml"
          target: "services/demos/"
      - uses: appleboy/ssh-action@master
        env:
          DOCKER_IMAGE: bcblr/demos:${{ needs.build-image.outputs.tag }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          envs: DOCKER_IMAGE
          script: |
            cd ~/services/demos/
            docker pull "$DOCKER_IMAGE"
            DOCKER_IMAGE="$DOCKER_IMAGE" docker-compose down
            DOCKER_IMAGE="$DOCKER_IMAGE" docker-compose up -d