name: deploy springboot demos
on:
  push:
    tags:
      - v*
  workflow_dispatch: {}

jobs:
  build-springboot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn package -DskipTests
      - uses: actions/upload-artifact@v2
        with:
          name: demos.jar
          path: target/*.jar

  build-image:
    runs-on: ubuntu-latest
    needs:
      - build-springboot
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: demos.jar
          path: target/
      - id: publish-docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: bcblr/demos
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_semver: true
    outputs:
      tag: ${{ steps.publish-docker.outputs.tag }}